spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/TestQuiz
    username: postgres
    password: 12121212
  flyway:
    baseline-on-migrate: true